<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BukuTamusSeeder extends Seeder
{
    public function run()
    {
        DB::table('buku_tamus')->insert([
            [
                'id_buku_tamu' => 1,
                'id_layanan' => 1,
                'id_bidang' => 3,
                'nip' => 101,
                'nama_pegawai' => 'Budi Santoso',
                'jabatan_pegawai' => 'Manager',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Konsultasi Anggaran',
                'createAdd' => '2024-10-13',
                'updateAdd' => '2024-10-13',
                'userAdd' => 1,
                'created_at' => '2024-10-13',
                'updated_at' => '2024-10-13',
            ],
            [
                'id_buku_tamu' => 2,
                'id_layanan' => 1,
                'id_bidang' => 2,
                'nip' => 102,
                'nama_pegawai' => 'Siti Aminah',
                'jabatan_pegawai' => 'Staf Administrasi',
                'unit_kerja_pegawai' => 'SDM',
                'tujuan_informasi' => 'Data Pegawai',
                'createAdd' => '2024-10-13',
                'updateAdd' => '2024-10-13',
                'userAdd' => 1,
                'created_at' => '2024-10-13',
                'updated_at' => '2024-10-13',
            ],
            [
                'id_buku_tamu' => 3,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 103,
                'nama_pegawai' => 'Ahmad Zaki',
                'jabatan_pegawai' => 'Koordinator',
                'unit_kerja_pegawai' => 'Logistik',
                'tujuan_informasi' => 'Distribusi Barang',
                'createAdd' => '2024-10-14',
                'updateAdd' => '2024-10-14',
                'userAdd' => 1,
                'created_at' => '2024-10-14',
                'updated_at' => '2024-10-14',
            ],
            [
                'id_buku_tamu' => 4,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 104,
                'nama_pegawai' => 'Ratna Dewi',
                'jabatan_pegawai' => 'Supervisor',
                'unit_kerja_pegawai' => 'Operasional',
                'tujuan_informasi' => 'Evaluasi Proyek',
                'createAdd' => '2024-10-12',
                'updateAdd' => '2024-10-12',
                'userAdd' => 1,
                'created_at' => '2024-10-12',
                'updated_at' => '2024-10-12',
            ],
            [
                'id_buku_tamu' => 5,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 105,
                'nama_pegawai' => 'Yusuf Pratama',
                'jabatan_pegawai' => 'Analis',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Audit Internal',
                'createAdd' => '2024-10-13',
                'updateAdd' => '2024-10-13',
                'userAdd' => 1,
                'created_at' => '2024-10-13',
                'updated_at' => '2024-10-13',
            ],
            [
                'id_buku_tamu' => 6,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 106,
                'nama_pegawai' => 'Dian Sari',
                'jabatan_pegawai' => 'Staf',
                'unit_kerja_pegawai' => 'SDM',
                'tujuan_informasi' => 'Pelatihan Pegawai',
                'createAdd' => '2024-10-11',
                'updateAdd' => '2024-10-11',
                'userAdd' => 1,
                'created_at' => '2024-10-11',
                'updated_at' => '2024-10-11',
            ],
            [
                'id_buku_tamu' => 7,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 107,
                'nama_pegawai' => 'Farhan Aditya',
                'jabatan_pegawai' => 'Kepala Divisi',
                'unit_kerja_pegawai' => 'Logistik',
                'tujuan_informasi' => 'Pengadaan Barang',
                'createAdd' => '2024-10-07',
                'updateAdd' => '2024-10-07',
                'userAdd' => 1,
                'created_at' => '2024-10-07',
                'updated_at' => '2024-10-07',
            ],
            [
                'id_buku_tamu' => 8,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 108,
                'nama_pegawai' => 'Lina Kurnia',
                'jabatan_pegawai' => 'Asisten',
                'unit_kerja_pegawai' => 'Operasional',
                'tujuan_informasi' => 'Evaluasi Kerja',
                'createAdd' => '2024-10-14',
                'updateAdd' => '2024-10-14',
                'userAdd' => 1,
                'created_at' => '2024-10-14',
                'updated_at' => '2024-10-14',
            ],
            [
                'id_buku_tamu' => 9,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 109,
                'nama_pegawai' => 'Rizal Fikri',
                'jabatan_pegawai' => 'Konsultan',
                'unit_kerja_pegawai' => 'Finance',
                'tujuan_informasi' => 'Konsultasi Laporan',
                'createAdd' => '2024-10-13',
                'updateAdd' => '2024-10-13',
                'userAdd' => 1,
                'created_at' => '2024-10-13',
                'updated_at' => '2024-10-13',
            ],
            [
                'id_buku_tamu' => 10,
                'id_layanan' => 1,
                'id_bidang' => 1,
                'nip' => 110,
                'nama_pegawai' => 'Andi Rahmat',
                'jabatan_pegawai' => 'Supervisor',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Pemantauan Anggaran',
                'createAdd' => '2024-10-13',
                'updateAdd' => '2024-10-13',
                'userAdd' => 1,
                'created_at' => '2024-10-13',
                'updated_at' => '2024-10-13',
            ],
        ]);
    }
}
