<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DashboardAdminsSeeder extends Seeder
{
    public function run()
    {
        DB::table('dashboard_admins')->insert([
            [
                'id_dashboard_admin' => 1,
                'id_buku_tamu' => 1,
                'id_admin' => 1,
                'nik' => 101,
                'nama_pegawai' => 'Budi Santoso',
                'jabatan_pegawai' => 'Manager',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Konsultasi Anggaran',
                'id_bidang' => 3,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-13 22:56:36',
                'updatedAdd' => '2024-10-13 23:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-13 22:56:36',
                'updated_at' => '2024-10-13 23:56:36',
            ],
            [
                'id_dashboard_admin' => 2,
                'id_buku_tamu' => 2,
                'id_admin' => 1,
                'nik' => 102,
                'nama_pegawai' => 'Siti Aminah',
                'jabatan_pegawai' => 'Staf Administrasi',
                'unit_kerja_pegawai' => 'SDM',
                'tujuan_informasi' => 'Data Pegawai',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-13 03:56:36',
                'updatedAdd' => '2024-10-13 04:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-13 03:56:36',
                'updated_at' => '2024-10-13 04:56:36',
            ],
            [
                'id_dashboard_admin' => 3,
                'id_buku_tamu' => 3,
                'id_admin' => 1,
                'nik' => 103,
                'nama_pegawai' => 'Ahmad Zaki',
                'jabatan_pegawai' => 'Koordinator',
                'unit_kerja_pegawai' => 'Logistik',
                'tujuan_informasi' => 'Distribusi Barang',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 2,
                'createdAdd' => '2024-10-14 03:26:36',
                'updatedAdd' => '2024-10-14 03:46:36',
                'userAdd' => 1,
                'created_at' => '2024-10-14 03:26:36',
                'updated_at' => '2024-10-14 03:46:36',
            ],
            [
                'id_dashboard_admin' => 4,
                'id_buku_tamu' => 4,
                'id_admin' => 1,
                'nik' => 104,
                'nama_pegawai' => 'Ratna Dewi',
                'jabatan_pegawai' => 'Supervisor',
                'unit_kerja_pegawai' => 'Operasional',
                'tujuan_informasi' => 'Evaluasi Proyek',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 2,
                'createdAdd' => '2024-10-12 03:56:36',
                'updatedAdd' => '2024-10-12 04:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-12 03:56:36',
                'updated_at' => '2024-10-12 04:56:36',
            ],
            [
                'id_dashboard_admin' => 5,
                'id_buku_tamu' => 5,
                'id_admin' => 1,
                'nik' => 105,
                'nama_pegawai' => 'Yusuf Pratama',
                'jabatan_pegawai' => 'Analis',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Audit Internal',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-13 19:56:36',
                'updatedAdd' => '2024-10-13 20:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-13 19:56:36',
                'updated_at' => '2024-10-13 20:56:36',
            ],
            [
                'id_dashboard_admin' => 6,
                'id_buku_tamu' => 6,
                'id_admin' => 1,
                'nik' => 106,
                'nama_pegawai' => 'Dian Sari',
                'jabatan_pegawai' => 'Staf',
                'unit_kerja_pegawai' => 'SDM',
                'tujuan_informasi' => 'Pelatihan Pegawai',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-11 03:56:36',
                'updatedAdd' => '2024-10-11 04:41:36',
                'userAdd' => 1,
                'created_at' => '2024-10-11 03:56:36',
                'updated_at' => '2024-10-11 04:41:36',
            ],
            [
                'id_dashboard_admin' => 7,
                'id_buku_tamu' => 7,
                'id_admin' => 1,
                'nik' => 107,
                'nama_pegawai' => 'Farhan Aditya',
                'jabatan_pegawai' => 'Kepala Divisi',
                'unit_kerja_pegawai' => 'Logistik',
                'tujuan_informasi' => 'Pengadaan Barang',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 2,
                'createdAdd' => '2024-10-07 03:56:36',
                'updatedAdd' => '2024-10-07 05:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-07 03:56:36',
                'updated_at' => '2024-10-07 05:56:36',
            ],
            [
                'id_dashboard_admin' => 8,
                'id_buku_tamu' => 8,
                'id_admin' => 1,
                'nik' => 108,
                'nama_pegawai' => 'Lina Kurnia',
                'jabatan_pegawai' => 'Asisten',
                'unit_kerja_pegawai' => 'Operasional',
                'tujuan_informasi' => 'Evaluasi Kerja',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-14 02:26:36',
                'updatedAdd' => '2024-10-14 03:26:36',
                'userAdd' => 1,
                'created_at' => '2024-10-14 02:26:36',
                'updated_at' => '2024-10-14 03:26:36',
            ],
            [
                'id_dashboard_admin' => 9,
                'id_buku_tamu' => 9,
                'id_admin' => 1,
                'nik' => 109,
                'nama_pegawai' => 'Rizal Fikri',
                'jabatan_pegawai' => 'Konsultan',
                'unit_kerja_pegawai' => 'Finance',
                'tujuan_informasi' => 'Konsultasi Laporan',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-13 21:56:36',
                'updatedAdd' => '2024-10-13 22:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-13 21:56:36',
                'updated_at' => '2024-10-13 22:56:36',
            ],
            [
                'id_dashboard_admin' => 10,
                'id_buku_tamu' => 10,
                'id_admin' => 1,
                'nik' => 110,
                'nama_pegawai' => 'Andi Rahmat',
                'jabatan_pegawai' => 'Supervisor',
                'unit_kerja_pegawai' => 'Keuangan',
                'tujuan_informasi' => 'Pemantauan Anggaran',
                'id_bidang' => 1,
                'id_layanan' => 1,
                'id_status' => 1,
                'createdAdd' => '2024-10-13 15:56:36',
                'updatedAdd' => '2024-10-13 17:56:36',
                'userAdd' => 1,
                'created_at' => '2024-10-13 15:56:36',
                'updated_at' => '2024-10-13 17:56:36',
            ],
            ]);
        }
    }
